const mockData = [
  {
    article_id: 1,
    writer: "user123",
    house_name: "햇살가득 아파트",
    house_type: "전세",
    house_year: 2022,
    house_price: 300000000,
    building_type: "아파트",
    house_floor: 15,
    score_outside: 4,
    score_inside: 5,
    score_traffic: 4,
    score_crime: 3,
    good: "전망이 좋고 햇살이 잘 들어옵니다.",
    bad: "주변 상가가 부족합니다.",
    img_url: "https://example.com/images/house1_1.jpg",
    address: "서울특별시 강남구 테헤란로 123",
    lat: 37.5665,
    lng: 126.978
  },
  {
    article_id: 2,
    writer: "user456",
    house_name: "햇살가득 아파트",
    house_type: "월세",
    house_year: 2023,
    house_price: 1500000,
    building_type: "아파트",
    house_floor: 10,
    score_outside: 3,
    score_inside: 4,
    score_traffic: 5,
    score_crime: 3,
    good: "교통이 매우 편리합니다.",
    bad: "층간 소음이 조금 있어요.",
    img_url: "https://example.com/images/house1_2.jpg",
    address: "서울특별시 강남구 테헤란로 123",
    lat: 37.5665,
    lng: 126.978
  },
  {
    article_id: 3,
    writer: "user789",
    house_name: "햇살가득 아파트",
    house_type: "전세",
    house_year: 2022,
    house_price: 320000000,
    building_type: "아파트",
    house_floor: 18,
    score_outside: 5,
    score_inside: 4,
    score_traffic: 4,
    score_crime: 3,
    good: "고층에서 바라보는 도시 전경이 멋집니다.",
    bad: "엘리베이터 대기 시간이 길어요.",
    img_url: "https://example.com/images/house1_3.jpg",
    address: "서울특별시 강남구 테헤란로 123",
    lat: 37.5665,
    lng: 126.978
  },
  {
    article_id: 4,
    writer: "user101",
    house_name: "햇살가득 아파트",
    house_type: "매매",
    house_year: 2022,
    house_price: 900000000,
    building_type: "아파트",
    house_floor: 12,
    score_outside: 4,
    score_inside: 5,
    score_traffic: 5,
    score_crime: 3,
    good: "인테리어가 고급스럽고 교통이 편리해요.",
    bad: "주차 공간이 부족한 편입니다.",
    img_url: "https://example.com/images/house1_4.jpg",
    address: "서울특별시 강남구 테헤란로 123",
    lat: 37.5665,
    lng: 126.978
  },
  {
    article_id: 5,
    writer: "user202",
    house_name: "햇살가득 아파트",
    house_type: "월세",
    house_year: 2022,
    house_price: 1300000,
    building_type: "아파트",
    house_floor: 8,
    score_outside: 3,
    score_inside: 4,
    score_traffic: 5,
    score_crime: 4,
    good: "대중교통 이용이 매우 편리해요.",
    bad: "창문이 작아 채광이 부족합니다.",
    img_url: "https://example.com/images/house1_5.jpg",
    address: "서울특별시 강남구 테헤란로 123",
    lat: 37.5665,
    lng: 126.978
  },
  {
    article_id: 6,
    writer: "user303",
    house_name: "햇살가득 아파트",
    house_type: "전세",
    house_year: 2023,
    house_price: 350000000,
    building_type: "아파트",
    house_floor: 20,
    score_outside: 5,
    score_inside: 5,
    score_traffic: 4,
    score_crime: 3,
    good: "최상층에서 도시 전체를 조망할 수 있어요.",
    bad: "바람이 강한 날엔 소음이 있습니다.",
    img_url: "https://example.com/images/house1_6.jpg",
    address: "서울특별시 강남구 테헤란로 123",
    lat: 37.5665,
    lng: 126.978
  },
  {
    article_id: 7,
    writer: "user404",
    house_name: "햇살가득 아파트",
    house_type: "매매",
    house_year: 2022,
    house_price: 850000000,
    building_type: "아파트",
    house_floor: 5,
    score_outside: 4,
    score_inside: 5,
    score_traffic: 5,
    score_crime: 4,
    good: "저층이라 접근성이 좋고 방음이 잘 돼요.",
    bad: "전망이 좋지 않습니다.",
    img_url: "https://example.com/images/house1_7.jpg",
    address: "서울특별시 강남구 테헤란로 123",
    lat: 37.5665,
    lng: 126.978
  },
  {
    article_id: 8,
    writer: "user505",
    house_name: "햇살가득 아파트",
    house_type: "월세",
    house_year: 2023,
    house_price: 1700000,
    building_type: "아파트",
    house_floor: 13,
    score_outside: 4,
    score_inside: 4,
    score_traffic: 5,
    score_crime: 3,
    good: "중간층이라 전망과 접근성이 균형 잡혀있어요.",
    bad: "주변 공사로 소음이 있습니다.",
    img_url: "https://example.com/images/house1_8.jpg",
    address: "서울특별시 강남구 테헤란로 123",
    lat: 37.5665,
    lng: 126.978
  },
  {
    article_id: 9,
    writer: "user606",
    house_name: "햇살가득 아파트",
    house_type: "전세",
    house_year: 2022,
    house_price: 280000000,
    building_type: "아파트",
    house_floor: 3,
    score_outside: 3,
    score_inside: 4,
    score_traffic: 5,
    score_crime: 4,
    good: "저층이라 계단 이용이 편리해요.",
    bad: "도로 소음이 들립니다.",
    img_url: "https://example.com/images/house1_9.jpg",
    address: "서울특별시 강남구 테헤란로 123",
    lat: 37.5665,
    lng: 126.978
  },
  {
    article_id: 10,
    writer: "user707",
    house_name: "햇살가득 아파트",
    house_type: "매매",
    house_year: 2023,
    house_price: 950000000,
    building_type: "아파트",
    house_floor: 17,
    score_outside: 5,
    score_inside: 5,
    score_traffic: 4,
    score_crime: 3,
    good: "최근 리모델링으로 내부 상태가 아주 좋아요.",
    bad: "주차장이 협소합니다.",
    img_url: "https://example.com/images/house1_10.jpg",
    address: "서울특별시 강남구 테헤란로 123",
    lat: 37.5665,
    lng: 126.978
  },
  {
    article_id: 11,
    writer: "user808",
    house_name: "도심속 오아시스 주택",
    house_type: "매매",
    house_year: 2021,
    house_price: 700000000,
    building_type: "주택/빌라",
    house_floor: 2,
    score_outside: 5,
    score_inside: 4,
    score_traffic: 3,
    score_crime: 5,
    good: "넓은 정원과 프라이버시가 보장됩니다.",
    bad: "대중교통 이용이 불편합니다.",
    img_url: "https://example.com/images/house2_1.jpg",
    address: "경기도 성남시 분당구 판교로 256번길 25",
    lat: 37.3947,
    lng: 127.1119
  },
  {
    article_id: 12,
    writer: "user909",
    house_name: "도심속 오아시스 주택",
    house_type: "매매",
    house_year: 2024,
    house_price: 750000000,
    building_type: "주택/빌라",
    house_floor: 2,
    score_outside: 4,
    score_inside: 5,
    score_traffic: 2,
    score_crime: 5,
    good: "최근 리모델링으로 내부가 매우 깔끔합니다.",
    bad: "주변 편의시설이 부족해요.",
    img_url: "https://example.com/images/house2_2.jpg",
    address: "경기도 성남시 분당구 판교로 256번길 25",
    lat: 37.3947,
    lng: 127.1119
  },
  {
    article_id: 13,
    writer: "user1010",
    house_name: "도심속 오아시스 주택",
    house_type: "전세",
    house_year: 2021,
    house_price: 400000000,
    building_type: "주택/빌라",
    house_floor: 2,
    score_outside: 5,
    score_inside: 3,
    score_traffic: 3,
    score_crime: 4,
    good: "조용한 주거환경과 넓은 마당이 있어요.",
    bad: "내부 인테리어가 다소 오래되었습니다.",
    img_url: "https://example.com/images/house2_3.jpg",
    address: "경기도 성남시 분당구 판교로 256번길 25",
    lat: 37.3947,
    lng: 127.1119
  },
  {
    article_id: 14,
    writer: "user1111",
    house_name: "강변 뷰 오피스텔",
    house_type: "전세",
    house_year: 2022,
    house_price: 250000000,
    building_type: "오피스텔",
    house_floor: 8,
    score_outside: 5,
    score_inside: 3,
    score_traffic: 4,
    score_crime: 4,
    good: "한강 뷰가 아름답고 편의시설이 가까워요.",
    bad: "실내 공간이 좁은 편입니다.",
    img_url: "https://example.com/images/house3_1.jpg",
    address: "서울특별시 용산구 이촌로 302",
    lat: 37.5229,
    lng: 126.9731
  },
  {
    article_id: 15,
    writer: "user1212",
    house_name: "강변 뷰 오피스텔",
    house_type: "월세",
    house_year: 2022,
    house_price: 1000000,
    building_type: "오피스텔",
    house_floor: 12,
    score_outside: 5,
    score_inside: 4,
    score_traffic: 4,
    score_crime: 3,
    good: "높은 층에서 한강 전망이 끝내줍니다.",
    bad: "주차 공간이 제한적입니다.",
    img_url: "https://example.com/images/house3_2.jpg",
    address: "서울특별시 용산구 이촌로 302",
    lat: 37.5229,
    lng: 126.9731
  },
  {
    article_id: 16,
    writer: "user1313",
    house_name: "도심 중심 빌라",
    house_type: "매매",
    house_year: 2020,
    house_price: 550000000,
    building_type: "주택/빌라",
    house_floor: 4,
    score_outside: 4,
    score_inside: 4,
    score_traffic: 5,
    score_crime: 3,
    good: "도심 접근성이 뛰어나고 인테리어가 현대적입니다.",
    bad: "주변이 번잡해 소음이 있을 수 있어요.",
    img_url: "https://example.com/images/house4_1.jpg",
    address: "서울특별시 마포구 와우산로 94",
    lat: 37.5536,
    lng: 126.9258
  },
  {
    article_id: 17,
    writer: "user2424",
    house_name: "역세권 신축 원룸",
    house_type: "월세",
    house_year: 2023,
    house_price: 10000000,
    monthly_rent: 500000,
    building_type: "원/투룸",
    house_floor: 3,
    score_outside: 3,
    score_inside: 5,
    score_traffic: 5,
    score_crime: 4,
    good: "역에서 가깝고 신축이라 깨끗해요. 편의시설도 가까워요.",
    bad: "주변에 유흥가가 있어 밤에 조금 시끄러울 수 있어요.",
    img_url: "https://example.com/images/oneroom7_1.jpg",
    address: "서울특별시 강남구 역삼로 123",
    lat: 37.4969,
    lng: 127.0378
  }
];

export default mockData;
