const mockData = [
  {
    article_id: 1,
    writer: "user123",
    house_name: "햇살가득 아파트",
    house_type: "전세",
    house_year: 2022,
    house_price: 300000000,
    building_type: "아파트",
    house_floor: 15,
    score_outside: 4,
    score_inside: 5,
    score_traffic: 4,
    score_crime: 3,
    good: "전망이 좋고 햇살이 잘 들어옵니다.",
    bad: "주변 상가가 부족합니다.",
    img_url: "https://example.com/images/house1_1.jpg",
    address: "서울특별시 강남구 테헤란로 123",
    lat: 37.5665,
    lng: 126.978
  },
  {
    article_id: 2,
    writer: "user456",
    house_name: "햇살가득 아파트",
    house_type: "월세",
    house_year: 2023,
    house_price: 1500000,
    building_type: "아파트",
    house_floor: 10,
    score_outside: 3,
    score_inside: 4,
    score_traffic: 5,
    score_crime: 3,
    good: "교통이 매우 편리합니다.",
    bad: "층간 소음이 조금 있어요.",
    img_url: "https://example.com/images/house1_2.jpg",
    address: "서울특별시 강남구 테헤란로 123",
    lat: 37.5665,
    lng: 126.978
  },
  {
    article_id: 3,
    writer: "user789",
    house_name: "도심속 오아시스 주택",
    house_type: "매매",
    house_year: 2021,
    house_price: 700000000,
    building_type: "단독주택",
    house_floor: 2,
    score_outside: 5,
    score_inside: 4,
    score_traffic: 3,
    score_crime: 5,
    good: "넓은 정원과 프라이버시가 보장됩니다.",
    bad: "대중교통 이용이 불편합니다.",
    img_url: "https://example.com/images/house2_1.jpg",
    address: "경기도 성남시 분당구 판교로 256번길 25",
    lat: 37.3947,
    lng: 127.1119
  },
  {
    article_id: 4,
    writer: "user101",
    house_name: "도심속 오아시스 주택",
    house_type: "매매",
    house_year: 2024,
    house_price: 750000000,
    building_type: "단독주택",
    house_floor: 2,
    score_outside: 4,
    score_inside: 5,
    score_traffic: 2,
    score_crime: 5,
    good: "최근 리모델링으로 내부가 매우 깔끔합니다.",
    bad: "주변 편의시설이 부족해요.",
    img_url: "https://example.com/images/house2_2.jpg",
    address: "경기도 성남시 분당구 판교로 256번길 25",
    lat: 37.3947,
    lng: 127.1119
  },
  {
    article_id: 5,
    writer: "user202",
    house_name: "강변 뷰 오피스텔",
    house_type: "전세",
    house_year: 2022,
    house_price: 250000000,
    building_type: "오피스텔",
    house_floor: 8,
    score_outside: 5,
    score_inside: 3,
    score_traffic: 4,
    score_crime: 4,
    good: "한강 뷰가 아름답고 편의시설이 가까워요.",
    bad: "실내 공간이 좁은 편입니다.",
    img_url: "https://example.com/images/house3_1.jpg",
    address: "서울특별시 용산구 이촌로 302",
    lat: 37.5229,
    lng: 126.9731
  }
];

export default mockData;
